name: CI

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [published]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: CMake configure and build
      run: |
        cmake -B build -A Win32
        cmake --build build --config ${{env.BUILD_TYPE}}

    - name: Install
      run: cmake --install build --prefix D2.Detours-Win32

    - name: Artifact
      uses: actions/upload-artifact@v2.2.1
      with:
        path: D2.Detours-Win32/*

    - name: Upload release
      if: github.event == 'release' && success()
      uses: alexellis/upload-assets@0.2.2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        asset_paths: '[ "D2.Detours-Win32/*" ]'
